(domain business weapons inn apothecary "magic items" outfitter)
(domain religion monotheist pantheist cthulian)
(domain race human insectoid electroid)
(domain nationality usian themian)
(domain physical scar fat tall short ugly pretty)
(domain emotional grumpy suspicious unscrupulous "overly friendly" bored)
(variable business business)
(variable religion religion (business apothecary))
(variable race race)
(variable nationality nationality (race human))
(variable physical physical)
(variable emotional emotional)
